/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JMenu;

/**
 *
 * @author Usser
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
         */
    //private ImageIcon imagen;
    //private Icon icono;
    public Menu() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
       //  this.centrarImgagenes(this.me, "/IMG/descarga.png");
         
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        GP = new javax.swing.JMenu();
        jEdicion = new javax.swing.JMenuItem();
        jDelete = new javax.swing.JMenuItem();
        jNuevo = new javax.swing.JMenuItem();
        Asin = new javax.swing.JMenu();
        jEdiciones2 = new javax.swing.JMenuItem();
        jDelete2 = new javax.swing.JMenuItem();
        jNuevos2 = new javax.swing.JMenuItem();
        Reser = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDelete3 = new javax.swing.JMenuItem();
        jNuevos3 = new javax.swing.JMenuItem();
        Avi = new javax.swing.JMenu();
        jEdiciones4 = new javax.swing.JMenuItem();
        jDelete4 = new javax.swing.JMenuItem();
        jNuevos4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        GP.setText("Getion de Pasajeros");

        jEdicion.setText("Ediciones");
        jEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdicionActionPerformed(evt);
            }
        });
        GP.add(jEdicion);

        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        GP.add(jDelete);

        jNuevo.setText("Nuevos");
        GP.add(jNuevo);

        jMenuBar1.add(GP);

        Asin.setText("Asientos");

        jEdiciones2.setText("Ediciones");
        Asin.add(jEdiciones2);

        jDelete2.setText("Delete");
        Asin.add(jDelete2);

        jNuevos2.setText("Nuevos");
        Asin.add(jNuevos2);

        jMenuBar1.add(Asin);

        Reser.setText("Reservas");

        jMenuItem1.setText("Ediciones");
        Reser.add(jMenuItem1);

        jDelete3.setText("Delete");
        Reser.add(jDelete3);

        jNuevos3.setText("Nuevos");
        Reser.add(jNuevos3);

        jMenuBar1.add(Reser);

        Avi.setText("Aviones");

        jEdiciones4.setText("Ediciones");
        Avi.add(jEdiciones4);

        jDelete4.setText("Delete");
        Avi.add(jDelete4);

        jNuevos4.setText("Nuevos");
        Avi.add(jNuevos4);

        jMenuBar1.add(Avi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEdicionActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDeleteActionPerformed
/*
    public void centrarImgagenes(JMenu label, String rutaImagen) {

        label.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(rutaImagen)).getImage()
                .getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT)));
    } 
  */  
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Asin;
    private javax.swing.JMenu Avi;
    private javax.swing.JMenu GP;
    private javax.swing.JMenu Reser;
    private javax.swing.JMenuItem jDelete;
    private javax.swing.JMenuItem jDelete2;
    private javax.swing.JMenuItem jDelete3;
    private javax.swing.JMenuItem jDelete4;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenuItem jEdicion;
    private javax.swing.JMenuItem jEdiciones2;
    private javax.swing.JMenuItem jEdiciones4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jNuevo;
    private javax.swing.JMenuItem jNuevos2;
    private javax.swing.JMenuItem jNuevos3;
    private javax.swing.JMenuItem jNuevos4;
    // End of variables declaration//GEN-END:variables
}
